### ISSUE TITLE
Play an emote Action

### ISSUE THREAD

**Issue by nearnshaw** [decentraland/smart-items#37]
Make the player perform an emote

This should support 
- A dropdown of default emotes
- Fetching an emote from a file

From the SDK each is done via a different function

It's no longer necessary to handle any permissions to do this

**Comment by cazala** [comment]
This has been implemented on the `@dcl/asset-packs` package and the UI as well in `@dcl/inspector`, but the custom emote feature is disabled for now due to this bug: https://github.com/decentraland/sdk/issues/1042, only the default emotes are enabled. Once that bug is fixed the custom emote feature can be turned on by flipping a switch.
